### ISSUE TITLE
NEXT_PUBLIC_SUPPORTED_TOKEN Modification Error

### ISSUE THREAD

**Issue by aperire** [askibin/twap#69]
If owner wants to remove certain token from UI when pair exists in program, owner can remove the public key of token from NEXT_PUBLIC_SUPPORTED_TOKEN. 

However, this raises runtime error at `app/src/organisms/coin-select.tsx - populateTokenRecords` as `token.symbol` is undefined.

If we add try/catch block as follows, the error does not occur when toggling token list on Trade. However, if user had existing TIF order for this token, cancelling/withdrawing on Orders section does not work.

```js
const populateTokenRecords = (data?: JupToken[]) => {
  if (!data) return {};

  const records: Record<string, TokenInfo> = {};
  data.forEach((token) => {
    // Add try/catch
    try{
      records[token.symbol.toLowerCase()] = {
        ...token,
        image: token.logoURI,
      };
    } catch(error){}

  });

  return records;
};
```

There should be flexibility on removing certain tokens from Trade section but not affecting existing orders on Orders section.

**Comment by rogaldh** [comment]
We talked recently about the issue with `NEXT_PUBLIC_SUPPORT_TOKEN.` There is an idea to eliminate this workaround with the environment variable. We want to start using the list of token pairs (all the pairs with the `allowDeposits` setting enabled).

How about that?

**Comment by askibin** [comment]
sounds good with me!

**Comment by rogaldh** [comment]
Here is the candidate: https://github.com/solana-labs/twamm/pull/3

**Comment by rogaldh** [comment]
I’m closing the issue. Feel free to write again
